# Generated by Django 2.2 on 2020-01-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200101_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user_id',
            field=models.CharField(default='Samiser', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='user_id',
            field=models.CharField(default='Samiser', max_length=200),
            preserve_default=False,
        ),
    ]
